build:
  version: "1.0"

loans:
  message: "Welcome to the Loans Service APIs production support team of JK Bank"
  contactDetails:
    name: "Laura - Product Manager"
    email: "jk@jkbank.com"
  onCallSupport:
    - 1800-123-456
    - 1800-987-000

# --- Kafka & Messaging Configuration ---
spring:
  application:
    name: loans
  cloud:
    function:
      definition: updateCommunication
    stream:
      default-binder: kafka
      bindings:
        # Input: Receive feedback from Message Service
        updateCommunication-in-0:
          destination: feedback-loan-communication-sent
          group: loans
        
        # Output: Send SMS/Email request to Message Service
        sendCommunication-out-0:
          destination: send-loan-communication
      kafka:
        binder:
          brokers:
            - kafka:9092


